name: stories_lib_example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.6+1

  cupertino_icons: ^0.1.2
  stories_lib:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
